### ISSUE TITLE
Hangman input

### ISSUE THREAD

**Issue by DustinTheGreat** [ichabod801/t_games#338]
When entering how many games you want to play if you enter anything but an INT you get a Type error and the program exits. Maybe trying to catch the exception and recursively call it until it gets a valid answer.

**Comment by ichabod801** [comment]
I'm confused. Hangman doesn't ask you how many games to play. Please clarify the exact question you are responding to in hangman, and how you are responding.

**Comment by DustinTheGreat** [comment]
Sorry I meant when responding to: "Think of a word for me to guess. How many letters are in it?"
When answering with a  random string input it i.r "fdsahfkdjs" it  just breaks the code and exists with   
"TypeError: can't multiply sequence by non-int of type 'str' "
I thought it could be like the number guessing game where your prompt invalid input and let you try to enter again with valid input.

**Comment by ichabod801** [comment]
No, I have that. It uses the ask_int method of the player. For a human player it can make sure the value is an integer, and can do other things like restrict the range of the results. However, the method could be used when there is also the possibility of handling other commands, so non-integer responses are return to be passed to the handle_cmd method. So I either need to set the option to block other text from ask_int for that call, or I need to add code to handle other commands.

I will add this ticket to the current project.

**Comment by ichabod801** [comment]
I opted to add command handling at that point. It seemed unlikely but possible that someone might want to do some RPN calculations at that point. And it is the start of the game, so they might want to check the rules or some other help.
